In [1]:
# importamos las librerías que necesitamos

# Tratamiento de datos
# -----------------------------------------------------------------------
import pandas as pd
import numpy as np

# Visualización
# ------------------------------------------------------------------------------
import matplotlib.pyplot as plt
import seaborn as sns

# Evaluar linealidad de las relaciones entre las variables
# ------------------------------------------------------------------------------
from scipy.stats import shapiro, kstest

# Configuración
# -----------------------------------------------------------------------
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

# Gestión de los warnings
# -----------------------------------------------------------------------
import warnings
warnings.filterwarnings("ignore")

In [4]:
# lo primero que hacemos es cargar el dataframe que vamos a usar para esta lección
df = pd.read_csv("archivos/world_data_full_apply_nulos.csv",index_col=0) 
df.head(2)

,country,density,abbreviation,agricultural_land,land_area,armed_forces_size,birth_rate,calling_code,capital/major_city,co2-emissions,cpi,cpi_change,currency-code,fertility_rate,forested_area,gasoline_price,gdp,gross_primary_education_enrollment,gross_tertiary_education_enrollment,infant_mortality,largest_city,life_expectancy,maternal_mortality_ratio,minimum_wage,official_language,out_of_pocket_health_expenditure,physicians_per_thousand,population,population_labor_force_participation,tax_revenue,total_tax_rate,unemployment_rate,urban_population,latitude,longitude,continent
0,Afghanistan,60.0,AF,58.1,652.230,323.0,32.49,93.0,Kabul,8.672,149.90,2.3,AFN,4.47,2.1,0.70,1.910135e+10,104.0,9.7,47.9,Kabul,64.5,638.0,0.43,Pashto,78.4,0.28,NaN,48.9,9.3,71.4,11.12,NaN,33.939110,67.709953,Asia
1,Albania,105.0,AL,43.1,28.748,9.0,11.78,355.0,Tirana,4.536,119.05,1.4,ALL,1.62,28.1,1.36,1.527808e+10,107.0,55.0,7.8,Tirana,78.5,15.0,1.12,Albanian,56.9,1.20,NaN,55.7,18.6,36.6,12.33,NaN,41.153332,20.168331,Europe

1.Calcula las siguientes estadísticas descriptivas para las variables numéricas:

Media

Mediana

Desviación estándar

Mínimo

Máximo

In [6]:
from itertools import combinations

# definimos la lista los nombres de las variables numéricas 
numericas = df.select_dtypes(include = np.number).columns
numericas

Index(['density', 'agricultural_land', 'land_area', 'armed_forces_size',
       'birth_rate', 'calling_code', 'co2-emissions', 'cpi', 'cpi_change',
       'fertility_rate', 'forested_area', 'gasoline_price', 'gdp',
       'gross_primary_education_enrollment',
       'gross_tertiary_education_enrollment', 'infant_mortality',
       'life_expectancy', 'maternal_mortality_ratio', 'minimum_wage',
       'out_of_pocket_health_expenditure', 'physicians_per_thousand',
       'population', 'population_labor_force_participation', 'tax_revenue',
       'total_tax_rate', 'unemployment_rate', 'urban_population', 'latitude',
       'longitude'],
      dtype='object')

In [25]:
for columna in numericas:
   
    print(f"la media de la {columna} es {df[columna].mean().round(2)}")
    print(f"la mediana de la {columna} es {df[columna].median()}")
    print(f"la desviación estandar de la {columna} es {df[columna].std()}")
    print(f"el min de la {columna} es {df[columna].min()}")
    print(f"el max de la {columna} es {df[columna].max()}")
    print ("----------------------------------------------------------")

la media de la density es 134.5
la mediana de la density es 83.0
la desviación estandar de la density es 157.3067742999071
el min de la density es 1.265
el max de la density es 847.0
----------------------------------------------------------
la media de la agricultural_land es 39.12
la mediana de la agricultural_land es 39.6
la desviación estandar de la agricultural_land es 21.783051852112166
el min de la agricultural_land es 0.6
el max de la agricultural_land es 82.6
----------------------------------------------------------
la media de la land_area es 255.21
la mediana de la land_area es 148.46
la desviación estandar de la land_area es 258.38500830296937
el min de la land_area es 0.0
el max de la land_area es 964.0
----------------------------------------------------------
la media de la armed_forces_size es 103.78
la mediana de la armed_forces_size es 28.5
la desviación estandar de la armed_forces_size es 167.15803070422805
el min de la armed_forces_size es 0.0
el max de la armed_forces_size es 936.0
----------------------------------------------------------
la media de la birth_rate es 20.21
la mediana de la birth_rate es 17.95
la desviación estandar de la birth_rate es 9.945773753600422
el min de la birth_rate es 5.9
el max de la birth_rate es 46.08
----------------------------------------------------------
la media de la calling_code es 360.55
la mediana de la calling_code es 255.5
la desviación estandar de la calling_code es 323.23641937558233
el min de la calling_code es 1.0
el max de la calling_code es 1876.0
----------------------------------------------------------
la media de la co2-emissions es 125.92
la mediana de la co2-emissions es 34.477
la desviación estandar de la co2-emissions es 181.794917134448
el min de la co2-emissions es 1.016
el max de la co2-emissions es 727.973
----------------------------------------------------------
la media de la cpi es 144.19
la mediana de la cpi es 124.74
la desviación estandar de la cpi es 54.78399814779379
el min de la cpi es 99.03
el max de la cpi es 550.93
----------------------------------------------------------
la media de la cpi_change es 6.72
la mediana de la cpi_change es 2.3
la desviación estandar de la cpi_change es 24.45041423496496
el min de la cpi_change es -4.3
el max de la cpi_change es 254.9
----------------------------------------------------------
la media de la fertility_rate es 2.7
la mediana de la fertility_rate es 2.245
la desviación estandar de la fertility_rate es 1.2822674777575596
el min de la fertility_rate es 0.98
el max de la fertility_rate es 6.91
----------------------------------------------------------
la media de la forested_area es 32.02
la mediana de la forested_area es 32.0
la desviación estandar de la forested_area es 23.791330518475522
el min de la forested_area es 0.0
el max de la forested_area es 98.3
----------------------------------------------------------
la media de la gasoline_price es 1.0
la mediana de la gasoline_price es 0.98
la desviación estandar de la gasoline_price es 0.3688584707290473
el min de la gasoline_price es 0.0
el max de la gasoline_price es 2.0
----------------------------------------------------------
la media de la gdp es 477295901399.54
la mediana de la gdp es 34387229486.0
la desviación estandar de la gdp es 2172173359474.053
el min de la gdp es 47271463.0
el max de la gdp es 21427700000000.0
----------------------------------------------------------
la media de la gross_primary_education_enrollment es 102.47
la mediana de la gross_primary_education_enrollment es 102.55
la desviación estandar de la gross_primary_education_enrollment es 13.151607370396855
el min de la gross_primary_education_enrollment es 23.4
el max de la gross_primary_education_enrollment es 142.5
----------------------------------------------------------
la media de la gross_tertiary_education_enrollment es 37.96
la mediana de la gross_tertiary_education_enrollment es 31.2
la desviación estandar de la gross_tertiary_education_enrollment es 29.261021657805045
el min de la gross_tertiary_education_enrollment es 0.8
el max de la gross_tertiary_education_enrollment es 136.6
----------------------------------------------------------
la media de la infant_mortality es 21.33
la mediana de la infant_mortality es 14.0
la desviación estandar de la infant_mortality es 19.548058157595797
el min de la infant_mortality es 1.4
el max de la infant_mortality es 84.5
----------------------------------------------------------
la media de la life_expectancy es 72.28
la mediana de la life_expectancy es 73.2
la desviación estandar de la life_expectancy es 7.48366061767797
el min de la life_expectancy es 52.8
el max de la life_expectancy es 85.4
----------------------------------------------------------
la media de la maternal_mortality_ratio es 160.39
la mediana de la maternal_mortality_ratio es 53.0
la desviación estandar de la maternal_mortality_ratio es 233.502024130785
el min de la maternal_mortality_ratio es 2.0
el max de la maternal_mortality_ratio es 1150.0
----------------------------------------------------------
la media de la minimum_wage es 2.19
la mediana de la minimum_wage es 1.045
la desviación estandar de la minimum_wage es 2.9707959267641972
el min de la minimum_wage es 0.01
el max de la minimum_wage es 13.59
----------------------------------------------------------
la media de la out_of_pocket_health_expenditure es 32.64
la mediana de la out_of_pocket_health_expenditure es 30.7
la desviación estandar de la out_of_pocket_health_expenditure es 19.172696629631496
el min de la out_of_pocket_health_expenditure es 0.2
el max de la out_of_pocket_health_expenditure es 81.6
----------------------------------------------------------
la media de la physicians_per_thousand es 1.84
la mediana de la physicians_per_thousand es 1.46
la desviación estandar de la physicians_per_thousand es 1.6842610452413442
el min de la physicians_per_thousand es 0.01
el max de la physicians_per_thousand es 8.42
----------------------------------------------------------
la media de la population es 333.54
la mediana de la population es 215.056
la desviación estandar de la population es 296.4675039945089
el min de la population es 10.084
el max de la population es 973.56
----------------------------------------------------------
la media de la population_labor_force_participation es 62.74
la mediana de la population_labor_force_participation es 62.45
la desviación estandar de la population_labor_force_participation es 10.502907065102585
el min de la population_labor_force_participation es 38.0
el max de la population_labor_force_participation es 86.8
----------------------------------------------------------
la media de la tax_revenue es 16.57
la mediana de la tax_revenue es 16.3
la desviación estandar de la tax_revenue es 6.961631857386574
el min de la tax_revenue es 0.0
el max de la tax_revenue es 37.2
----------------------------------------------------------
la media de la total_tax_rate es 40.82
la mediana de la total_tax_rate es 37.2
la desviación estandar de la total_tax_rate es 20.557661888432293
el min de la total_tax_rate es 8.0
el max de la total_tax_rate es 219.6
----------------------------------------------------------
la media de la unemployment_rate es 6.89
la mediana de la unemployment_rate es 5.36
la desviación estandar de la unemployment_rate es 5.079216403415715
el min de la unemployment_rate es 0.09
el max de la unemployment_rate es 28.18
----------------------------------------------------------
la media de la urban_population es 279.46
la mediana de la urban_population es 179.039
la desviación estandar de la urban_population es 283.322352165415
el min de la urban_population es 5.464
el max de la urban_population es 984.812
----------------------------------------------------------
la media de la latitude es 19.09
la mediana de la latitude es 17.273849499999997
la desviación estandar de la latitude es 23.961779464412047
el min de la latitude es -40.900557
el max de la latitude es 64.963051
----------------------------------------------------------
la media de la longitude es 20.23
la mediana de la longitude es 20.9726515
la desviación estandar de la longitude es 66.71611018000907
el min de la longitude es -175.198242
el max de la longitude es 178.065032
----------------------------------------------------------

In [13]:
# Suponiendo que 'numericas' contiene las columnas numéricas de tu DataFrame
for columna in numericas:
    print(f"\n📊 ESTADÍSTICAS PARA: '{columna.upper()}'")
    print("-" * 40)
    print(f"Media → {df[columna].mean():.2f}")
    print(f"Mediana → {df[columna].median():.2f}")
    print(f"Desviación estándar → {df[columna].std():.2f}")
    print(f"Mínimo → {df[columna].min():.2f}")
    print(f"Máximo → {df[columna].max():.2f}")
    print(f"Rango intercuartílico → {df[columna].quantile(0.75) - df[columna].quantile(0.25):.2f}")

📊 ESTADÍSTICAS PARA: 'DENSITY'
----------------------------------------
Media → 134.50
Mediana → 83.00
Desviación estándar → 157.31
Mínimo → 1.26
Máximo → 847.00
Rango intercuartílico → 139.33

📊 ESTADÍSTICAS PARA: 'AGRICULTURAL_LAND'
----------------------------------------
Media → 39.12
Mediana → 39.60
Desviación estándar → 21.78
Mínimo → 0.60
Máximo → 82.60
Rango intercuartílico → 33.67

📊 ESTADÍSTICAS PARA: 'LAND_AREA'
----------------------------------------
Media → 255.21
Mediana → 148.46
Desviación estándar → 258.39
Mínimo → 0.00
Máximo → 964.00
Rango intercuartílico → 388.72

📊 ESTADÍSTICAS PARA: 'ARMED_FORCES_SIZE'
----------------------------------------
Media → 103.78
Mediana → 28.50
Desviación estándar → 167.16
Mínimo → 0.00
Máximo → 936.00
Rango intercuartílico → 118.00

📊 ESTADÍSTICAS PARA: 'BIRTH_RATE'
----------------------------------------
Media → 20.21
Mediana → 17.95
Desviación estándar → 9.95
Mínimo → 5.90
Máximo → 46.08
Rango intercuartílico → 17.45

📊 ESTADÍSTICAS PARA: 'CALLING_CODE'
----------------------------------------
Media → 360.55
Mediana → 255.50
Desviación estándar → 323.24
Mínimo → 1.00
Máximo → 1876.00
Rango intercuartílico → 424.25

📊 ESTADÍSTICAS PARA: 'CO2-EMISSIONS'
----------------------------------------
Media → 125.92
Mediana → 34.48
Desviación estándar → 181.79
Mínimo → 1.02
Máximo → 727.97
Rango intercuartílico → 177.43

📊 ESTADÍSTICAS PARA: 'CPI'
----------------------------------------
Media → 144.19
Mediana → 124.74
Desviación estándar → 54.78
Mínimo → 99.03
Máximo → 550.93
Rango intercuartílico → 42.26

📊 ESTADÍSTICAS PARA: 'CPI_CHANGE'
----------------------------------------
Media → 6.72
Mediana → 2.30
Desviación estándar → 24.45
Mínimo → -4.30
Máximo → 254.90
Rango intercuartílico → 3.25

📊 ESTADÍSTICAS PARA: 'FERTILITY_RATE'
----------------------------------------
Media → 2.70
Mediana → 2.25
Desviación estándar → 1.28
Mínimo → 0.98
Máximo → 6.91
Rango intercuartílico → 1.89

📊 ESTADÍSTICAS PARA: 'FORESTED_AREA'
----------------------------------------
Media → 32.02
Mediana → 32.00
Desviación estándar → 23.79
Mínimo → 0.00
Máximo → 98.30
Rango intercuartílico → 37.17

📊 ESTADÍSTICAS PARA: 'GASOLINE_PRICE'
----------------------------------------
Media → 1.00
Mediana → 0.98
Desviación estándar → 0.37
Mínimo → 0.00
Máximo → 2.00
Rango intercuartílico → 0.48

📊 ESTADÍSTICAS PARA: 'GDP'
----------------------------------------
Media → 477295901399.54
Mediana → 34387229486.00
Desviación estándar → 2172173359474.05
Mínimo → 47271463.00
Máximo → 21427700000000.00
Rango intercuartílico → 225639423331.00

📊 ESTADÍSTICAS PARA: 'GROSS_PRIMARY_EDUCATION_ENROLLMENT'
----------------------------------------
Media → 102.47
Mediana → 102.55
Desviación estándar → 13.15
Mínimo → 23.40
Máximo → 142.50
Rango intercuartílico → 9.08

📊 ESTADÍSTICAS PARA: 'GROSS_TERTIARY_EDUCATION_ENROLLMENT'
----------------------------------------
Media → 37.96
Mediana → 31.20
Desviación estándar → 29.26
Mínimo → 0.80
Máximo → 136.60
Rango intercuartílico → 51.00

📊 ESTADÍSTICAS PARA: 'INFANT_MORTALITY'
----------------------------------------
Media → 21.33
Mediana → 14.00
Desviación estándar → 19.55
Mínimo → 1.40
Máximo → 84.50
Rango intercuartílico → 26.70

📊 ESTADÍSTICAS PARA: 'LIFE_EXPECTANCY'
----------------------------------------
Media → 72.28
Mediana → 73.20
Desviación estándar → 7.48
Mínimo → 52.80
Máximo → 85.40
Rango intercuartílico → 10.50

📊 ESTADÍSTICAS PARA: 'MATERNAL_MORTALITY_RATIO'
----------------------------------------
Media → 160.39
Mediana → 53.00
Desviación estándar → 233.50
Mínimo → 2.00
Máximo → 1150.00
Rango intercuartílico → 173.00

📊 ESTADÍSTICAS PARA: 'MINIMUM_WAGE'
----------------------------------------
Media → 2.19
Mediana → 1.04
Desviación estándar → 2.97
Mínimo → 0.01
Máximo → 13.59
Rango intercuartílico → 2.04

📊 ESTADÍSTICAS PARA: 'OUT_OF_POCKET_HEALTH_EXPENDITURE'
----------------------------------------
Media → 32.64
Mediana → 30.70
Desviación estándar → 19.17
Mínimo → 0.20
Máximo → 81.60
Rango intercuartílico → 26.52

📊 ESTADÍSTICAS PARA: 'PHYSICIANS_PER_THOUSAND'
----------------------------------------
Media → 1.84
Mediana → 1.46
Desviación estándar → 1.68
Mínimo → 0.01
Máximo → 8.42
Rango intercuartílico → 2.60

📊 ESTADÍSTICAS PARA: 'POPULATION'
----------------------------------------
Media → 333.54
Mediana → 215.06
Desviación estándar → 296.47
Mínimo → 10.08
Máximo → 973.56
Rango intercuartílico → 469.03

📊 ESTADÍSTICAS PARA: 'POPULATION_LABOR_FORCE_PARTICIPATION'
----------------------------------------
Media → 62.74
Mediana → 62.45
Desviación estándar → 10.50
Mínimo → 38.00
Máximo → 86.80
Rango intercuartílico → 13.35

📊 ESTADÍSTICAS PARA: 'TAX_REVENUE'
----------------------------------------
Media → 16.57
Mediana → 16.30
Desviación estándar → 6.96
Mínimo → 0.00
Máximo → 37.20
Rango intercuartílico → 9.40

📊 ESTADÍSTICAS PARA: 'TOTAL_TAX_RATE'
----------------------------------------
Media → 40.82
Mediana → 37.20
Desviación estándar → 20.56
Mínimo → 8.00
Máximo → 219.60
Rango intercuartílico → 17.40

📊 ESTADÍSTICAS PARA: 'UNEMPLOYMENT_RATE'
----------------------------------------
Media → 6.89
Mediana → 5.36
Desviación estándar → 5.08
Mínimo → 0.09
Máximo → 28.18
Rango intercuartílico → 6.10

📊 ESTADÍSTICAS PARA: 'URBAN_POPULATION'
----------------------------------------
Media → 279.46
Mediana → 179.04
Desviación estándar → 283.32
Mínimo → 5.46
Máximo → 984.81
Rango intercuartílico → 377.00

📊 ESTADÍSTICAS PARA: 'LATITUDE'
----------------------------------------
Media → 19.09
Mediana → 17.27
Desviación estándar → 23.96
Mínimo → -40.90
Máximo → 64.96
Rango intercuartílico → 35.58

📊 ESTADÍSTICAS PARA: 'LONGITUDE'
----------------------------------------
Media → 20.23
Mediana → 20.97
Desviación estándar → 66.72
Mínimo → -175.20
Máximo → 178.07
Rango intercuartílico → 56.22

2.Identifica el país con la mayor densidad de población y el país con la menor población en el conjunto de datos.

In [36]:
df.sort_values(["density","country"],ascending=True).head(1)

,country,density,abbreviation,agricultural_land,land_area,armed_forces_size,birth_rate,calling_code,capital/major_city,co2-emissions,cpi,cpi_change,currency-code,fertility_rate,forested_area,gasoline_price,gdp,gross_primary_education_enrollment,gross_tertiary_education_enrollment,infant_mortality,largest_city,life_expectancy,maternal_mortality_ratio,minimum_wage,official_language,out_of_pocket_health_expenditure,physicians_per_thousand,population,population_labor_force_participation,tax_revenue,total_tax_rate,unemployment_rate,urban_population,latitude,longitude,continent
13,Bangladesh,1.265,BD,70.6,148.46,221.0,18.18,880.0,Dhaka,84.246,179.68,5.6,BDT,2.04,11.0,1.12,3.025713e+11,116.5,20.6,25.1,Dhaka,72.3,173.0,0.51,Bengali,71.8,0.58,NaN,59.0,8.8,33.4,4.19,NaN,23.684994,90.356331,Asia

In [37]:
df.sort_values(["density","country"],ascending=False).head(1)

,country,density,abbreviation,agricultural_land,land_area,armed_forces_size,birth_rate,calling_code,capital/major_city,co2-emissions,cpi,cpi_change,currency-code,fertility_rate,forested_area,gasoline_price,gdp,gross_primary_education_enrollment,gross_tertiary_education_enrollment,infant_mortality,largest_city,life_expectancy,maternal_mortality_ratio,minimum_wage,official_language,out_of_pocket_health_expenditure,physicians_per_thousand,population,population_labor_force_participation,tax_revenue,total_tax_rate,unemployment_rate,urban_population,latitude,longitude,continent
133,Palestinian National Authority,847.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Arabic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.952162,35.233154,Asia

In [32]:
df.head(10)

,country,density,abbreviation,agricultural_land,land_area,armed_forces_size,birth_rate,calling_code,capital/major_city,co2-emissions,cpi,cpi_change,currency-code,fertility_rate,forested_area,gasoline_price,gdp,gross_primary_education_enrollment,gross_tertiary_education_enrollment,infant_mortality,largest_city,life_expectancy,maternal_mortality_ratio,minimum_wage,official_language,out_of_pocket_health_expenditure,physicians_per_thousand,population,population_labor_force_participation,tax_revenue,total_tax_rate,unemployment_rate,urban_population,latitude,longitude,continent
0,Afghanistan,60.0,AF,58.1,652.230,323.0,32.49,93.0,Kabul,8.672,149.90,2.3,AFN,4.47,2.1,0.70,1.910135e+10,104.0,9.7,47.9,Kabul,64.5,638.0,0.43,Pashto,78.4,0.28,NaN,48.9,9.3,71.4,11.12,NaN,33.939110,67.709953,Asia
1,Albania,105.0,AL,43.1,28.748,9.0,11.78,355.0,Tirana,4.536,119.05,1.4,ALL,1.62,28.1,1.36,1.527808e+10,107.0,55.0,7.8,Tirana,78.5,15.0,1.12,Albanian,56.9,1.20,NaN,55.7,18.6,36.6,12.33,NaN,41.153332,20.168331,Europe
2,Algeria,18.0,DZ,17.4,NaN,317.0,24.28,213.0,Algiers,150.006,151.36,2.0,DZD,3.02,0.8,0.28,1.699882e+11,109.9,51.4,20.1,Algiers,76.7,112.0,0.95,Arabic,28.1,1.72,NaN,41.2,37.2,66.1,11.70,NaN,28.033886,1.659626,Africa
3,Andorra,164.0,AD,40.0,468.000,NaN,7.20,376.0,Andorra la Vella,469.000,NaN,NaN,EUR,1.27,34.0,1.51,3.154058e+09,106.4,NaN,2.7,Andorra la Vella,NaN,NaN,6.63,Catalan,36.4,3.33,77.142,NaN,NaN,NaN,NaN,67.873,42.506285,1.521801,Europe
4,Angola,26.0,AO,47.5,NaN,117.0,40.73,244.0,Luanda,34.693,261.73,17.1,AOA,5.52,46.3,0.97,9.463542e+10,113.5,9.3,51.6,Luanda,60.8,241.0,0.71,Portuguese,33.4,0.21,NaN,77.5,9.2,49.1,6.89,NaN,-11.202692,17.873887,Africa
5,Antigua and Barbuda,223.0,AG,20.5,443.000,0.0,15.33,1.0,"St. John's, Saint John",557.000,113.81,1.2,XCD,1.99,22.3,0.99,1.727759e+09,105.0,24.8,5.0,"St. John's, Saint John",76.9,42.0,3.04,English,24.3,2.76,97.118,NaN,16.5,43.0,NaN,23.800,17.060816,-61.796428,Central America
6,Argentina,17.0,AR,54.3,NaN,105.0,17.02,54.0,Buenos Aires,201.348,232.75,53.5,ARS,2.26,9.8,1.10,4.496634e+11,109.7,90.0,8.8,Buenos Aires,76.5,39.0,3.35,Spanish,17.6,3.96,NaN,61.3,10.1,106.3,9.79,NaN,-38.416097,-63.616672,South America
7,Armenia,104.0,AM,58.9,29.743,49.0,13.99,374.0,Yerevan,5.156,129.18,1.4,AMD,1.76,11.7,0.77,1.367280e+10,92.7,54.6,11.0,Yerevan,74.9,26.0,0.66,Armenian,81.6,4.40,NaN,55.6,20.9,22.6,16.99,NaN,40.069099,45.038189,Asia
8,Australia,3.0,AU,48.2,NaN,58.0,12.60,61.0,Canberra,375.908,119.80,1.6,AUD,1.74,16.3,0.93,1.392681e+12,100.3,113.1,3.1,Sydney,82.7,6.0,13.59,NaN,19.6,3.68,NaN,65.5,23.0,47.4,5.27,NaN,-25.274398,133.775136,Oceania
9,Austria,109.0,AT,32.4,83.871,21.0,9.70,43.0,Vienna,61.448,118.06,1.5,EUR,1.47,46.9,1.20,4.463147e+11,103.1,85.1,2.9,Vienna,81.6,5.0,NaN,German,17.9,5.17,NaN,60.7,25.4,51.4,4.67,NaN,47.516231,14.550072,Europe

3.Calcula la tasa promedio de natalidad (birth_rate) para todos los países en el conjunto de datos.

In [38]:
df.groupby("country")["birth_rate"].mean()

country
Afghanistan    32.49
Albania        11.78
Algeria        24.28
Andorra         7.20
Angola         40.73
               ...
Venezuela      17.88
Vietnam        16.75
Yemen          30.45
Zambia         36.19
Zimbabwe       30.68
Name: birth_rate, Length: 195, dtype: float64

4.Realiza un análisis de la mortalidad infantil (infant_mortality) y clasifica los países en tres categorías: baja, moderada y alta mortalidad infantil.

In [40]:
df["infant_mortality"].describe()

count    189.000000
mean      21.332804
std       19.548058
min        1.400000
25%        6.000000
50%       14.000000
75%       32.700000
max       84.500000
Name: infant_mortality, dtype: float64

In [42]:

def mortalidad_infantil(infant_mortality):
    if infant_mortality < 14:
        return 'baja'
    elif infant_mortality < 32:
        return 'moderada'
    else:
        return 'alta'
df['categoria_mortalidad'] = df['infant_mortality'].apply(mortalidad_infantil)
display(df)

,country,density,abbreviation,agricultural_land,land_area,armed_forces_size,birth_rate,calling_code,capital/major_city,co2-emissions,cpi,cpi_change,currency-code,fertility_rate,forested_area,gasoline_price,gdp,gross_primary_education_enrollment,gross_tertiary_education_enrollment,infant_mortality,largest_city,life_expectancy,maternal_mortality_ratio,minimum_wage,official_language,out_of_pocket_health_expenditure,physicians_per_thousand,population,population_labor_force_participation,tax_revenue,total_tax_rate,unemployment_rate,urban_population,latitude,longitude,continent,categoria,categoria_mortalidad
0,Afghanistan,60.0,AF,58.1,652.230,323.0,32.49,93.0,Kabul,8.672,149.90,2.3,AFN,4.47,2.1,0.70,1.910135e+10,104.0,9.7,47.9,Kabul,64.5,638.0,0.43,Pashto,78.4,0.28,NaN,48.9,9.3,71.4,11.12,NaN,33.939110,67.709953,Asia,alta,alta
1,Albania,105.0,AL,43.1,28.748,9.0,11.78,355.0,Tirana,4.536,119.05,1.4,ALL,1.62,28.1,1.36,1.527808e+10,107.0,55.0,7.8,Tirana,78.5,15.0,1.12,Albanian,56.9,1.20,NaN,55.7,18.6,36.6,12.33,NaN,41.153332,20.168331,Europe,baja,baja
2,Algeria,18.0,DZ,17.4,NaN,317.0,24.28,213.0,Algiers,150.006,151.36,2.0,DZD,3.02,0.8,0.28,1.699882e+11,109.9,51.4,20.1,Algiers,76.7,112.0,0.95,Arabic,28.1,1.72,NaN,41.2,37.2,66.1,11.70,NaN,28.033886,1.659626,Africa,moderada,moderada
3,Andorra,164.0,AD,40.0,468.000,NaN,7.20,376.0,Andorra la Vella,469.000,NaN,NaN,EUR,1.27,34.0,1.51,3.154058e+09,106.4,NaN,2.7,Andorra la Vella,NaN,NaN,6.63,Catalan,36.4,3.33,77.142,NaN,NaN,NaN,NaN,67.873,42.506285,1.521801,Europe,baja,baja
4,Angola,26.0,AO,47.5,NaN,117.0,40.73,244.0,Luanda,34.693,261.73,17.1,AOA,5.52,46.3,0.97,9.463542e+10,113.5,9.3,51.6,Luanda,60.8,241.0,0.71,Portuguese,33.4,0.21,NaN,77.5,9.2,49.1,6.89,NaN,-11.202692,17.873887,Africa,alta,alta
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,32.0,VE,24.5,912.050,343.0,17.88,58.0,Caracas,164.175,NaN,254.9,VED,2.27,52.7,0.00,4.823593e+11,97.2,79.3,21.4,Caracas,72.1,125.0,0.01,Spanish,45.8,1.92,NaN,59.7,NaN,73.3,8.80,NaN,6.423750,-66.589730,South America,moderada,moderada
191,Vietnam,314.0,VN,39.3,331.210,522.0,16.75,84.0,Hanoi,192.668,163.52,2.8,VND,2.05,48.1,0.80,2.619212e+11,110.6,28.5,16.5,Ho Chi Minh City,75.3,43.0,0.73,Vietnamese,43.5,0.82,NaN,77.4,19.1,37.6,2.01,NaN,14.058324,108.277199,Asia,moderada,moderada
192,Yemen,56.0,YE,44.6,527.968,40.0,30.45,967.0,Sanaa,10.609,157.58,8.1,YER,3.79,1.0,0.92,2.691440e+10,93.6,10.2,42.9,Sanaa,66.1,164.0,NaN,Arabic,81.0,0.31,NaN,38.0,NaN,26.6,12.91,NaN,15.552727,48.516388,Asia,alta,alta
193,Zambia,25.0,ZM,32.1,752.618,16.0,36.19,260.0,Lusaka,5.141,212.31,9.2,ZMW,4.63,65.2,1.40,2.306472e+10,98.7,4.1,40.4,Lusaka,63.5,213.0,0.24,English,27.5,1.19,NaN,74.6,16.2,15.6,11.43,NaN,-13.133897,27.849332,Africa,alta,alta
194,Zimbabwe,38.0,ZW,41.9,390.757,51.0,30.68,263.0,Harare,10.983,105.51,0.9,NaN,3.62,35.5,1.34,2.144076e+10,109.9,10.0,33.9,Harare,61.2,458.0,NaN,Shona,25.8,0.21,NaN,83.1,20.7,31.6,4.95,NaN,-19.015438,29.154857,Africa,alta,alta